### ISSUE TITLE
ReferenceError: os is not defined

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#101]
v3 / dev branch 
I use node 10.x LTS

```
ReferenceError: os is not defined
    at Object.<anonymous> (/opt/multiparty-meeting/server/config/config.js:40:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/multiparty-meeting/server/server.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```
If I add to config the following one line, then it solves it.

`const os = require('os');`

**Comment by havfo** [comment]
https://github.com/havfo/multiparty-meeting/blob/develop/server/config/config.example.js#L1

**Comment by misi** [comment]
Sorry I  missed it.
