### ISSUE TITLE
Cannot find module './config/config'

### ISSUE THREAD

**Issue by kkar** [havfo/multiparty-meeting#90]
It is the second time I am setting up multiparty-meeting but the first time I get such an error. When I try to 'npm start' in the server directory I get the following error.

```
root@h2782615:~/multiparty-meeting/server# npm start

> multiparty-meeting-server@2.0.0 start /root/multiparty-meeting/server
> node server.js

module.js:550
    throw err;
    ^

Error: Cannot find module './config/config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/multiparty-meeting/server/server.js:7:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting-server@2.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting-server@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-10T17_45_24_701Z-debug.log
```

And when i 'cat' the log file mentioned in the last line, above... I get this.

```
root@h2782615:~/multiparty-meeting/server# cat /root/.npm/_logs/2019-05-10T17_45_24_701Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle multiparty-meeting-server@2.0.0~prestart: multiparty-meeting-server@2.0.0
6 info lifecycle multiparty-meeting-server@2.0.0~start: multiparty-meeting-server@2.0.0
7 verbose lifecycle multiparty-meeting-server@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle multiparty-meeting-server@2.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/multiparty-meeting/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle multiparty-meeting-server@2.0.0~start: CWD: /root/multiparty-meeting/server
10 silly lifecycle multiparty-meeting-server@2.0.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle multiparty-meeting-server@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle multiparty-meeting-server@2.0.0~start: Failed to exec start script
13 verbose stack Error: multiparty-meeting-server@2.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid multiparty-meeting-server@2.0.0
15 verbose cwd /root/multiparty-meeting/server
16 verbose Linux 4.9.0
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.16.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error multiparty-meeting-server@2.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the multiparty-meeting-server@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
root@h2782615:~/multiparty-meeting/server#

```

**Comment by misi** [comment]
@kkar 
Make sure your have server/config/config.js
Make sure you have copied the server/config/config.example.js to server/config/config.js

Thanks!!

**Comment by kkar** [comment]
Copied, edited, and fixed. Thank you.
