### ISSUE TITLE
Failed to minify the bundle

### ISSUE THREAD

**Issue by kkar** [havfo/multiparty-meeting#91]
```
root@h2782615:~/multiparty-meeting/app# npm run build

> multiparty-meeting@2.0.0 build /root/multiparty-meeting/app
> react-scripts build && rm -rf ../server/public/* && cp -r build/* ../server/public/

Creating an optimized production build...
Failed to compile.

Failed to minify the bundle. Error: static/js/main.792c278a.chunk.js from Terser
TypeError: child.send is not a function
    at compiler.run (/root/multiparty-meeting/app/node_modules/react-scripts/scripts/build.js:169:23)
    at finalCallback (/root/multiparty-meeting/app/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/root/multiparty-meeting/app/node_modules/webpack/lib/Compiler.js:226:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/multiparty-meeting/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/multiparty-meeting/app/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/root/multiparty-meeting/app/node_modules/webpack/lib/Compiler.js:224:21)
    at hooks.afterCompile.callAsync.err (/root/multiparty-meeting/app/node_modules/webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/multiparty-meeting/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/multiparty-meeting/app/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/root/multiparty-meeting/app/node_modules/webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/multiparty-meeting/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/multiparty-meeting/app/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/root/multiparty-meeting/app/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/multiparty-meeting/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/multiparty-meeting/app/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/root/multiparty-meeting/app/node_modules/webpack/lib/Compilation.js:1314:32)
Read more here: https://bit.ly/CRA-build-minify

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting@2.0.0 build: `react-scripts build && rm -rf ../server/public/* && cp -r build/* ../server/public/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-11T08_09_00_988Z-debug.log
root@h2782615:~/multiparty-meeting/app#
```

**Comment by kkar** [comment]
Tried to clean the cache, delete the lock file, delete node_modules folder and re-install with **npm install**. After **npm run build**, i got the following.

```
root@h2782615:~/multiparty-meeting/app# npm run build

> multiparty-meeting@2.0.0 build /root/multiparty-meeting/app
> react-scripts build && rm -rf ../server/public/* && cp -r build/* ../server/public/

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting@2.0.0 build: `react-scripts build && rm -rf ../server/public/* && cp -r build/* ../server/public/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-11T12_04_58_483Z-debug.log
root@h2782615:~/multiparty-meeting/app#

```

**Comment by havfo** [comment]
Is this running inside a docker container? What OS are you using, and which kernel?

**Comment by misi** [comment]
You can also try to use docker imagehttps://hub.docker.com/r/misi/mm/
Docker image:tag
 - misi/mm:latest  
   sync with https://github.com/havfo/multiparty-meeting/tree/master
 - misi/mm:dev  
   sync with https://github.com/havfo/multiparty-meeting/tree/develop
